### ISSUE TITLE
Un-init method? 

### ISSUE THREAD

**Issue by paulmsmith** [mzubala/jquery-custom-scrollbar#1]
Hi,

I love your custom scrollbar script but as part of a responsive site I need the ability to completely remove any DOM changes or events that the script has added when moving between breakpoints. I was going to use this along side jRespond.

Would it be easy for you to add such a "un-init" function/method?

**Comment by mzubala** [comment]
I added remove function:

$(el).customScrollbar("remove")

that removes dom changes and event bindings made by the plugin.

**Comment by paulmsmith** [comment]
Nice, thanks. :)
