### ISSUE TITLE
Firefox scrolls also in background

### ISSUE THREAD

**Issue by tobias-r** [mzubala/jquery-custom-scrollbar#13]
Hi!

I have an issue with your plugin.

If I have a layer display fixed on which I scroll, the firefox main window also scrolls.

You can see an example at
https://findpenguins.com/demo-account/74576545/worldtrip
Just click on the statistics icon and then scroll.

It's only in firefox - btw same in a picture popup.

Apart from it's all real great work, I chose your plugin over all these big time others. I like it simple.

Thank you
   Tobi

P.S. On more little thing, you should add something to the Function "calculateMaxOverviewPosition"

Instead of:
var y = this.sizing.size(this.scrollable.$overview) - this.sizing.size(this.scrollable.$viewPort);

Use:
var y = Math.max(0,this.sizing.size(this.scrollable.$overview) - this.sizing.size(this.scrollable.$viewPort));

Sometime it will get smaller than 0, and that we don't want :-)

**Comment by tobias-r** [comment]
the "var y =" at the bottom of my issue is of course wrong, cos you directly return. Sorry

**Comment by mzubala** [comment]
Hey

I tested your site on FF 17.0.1, 24.0 (windows) and 23.0 (linux). 
I did the following:
- open given url
- click statistics icon
- move the mouse over "This Map"
- scroll using mouse wheel

On all mentioned ff versions main window didn't scroll. Only custom scrollbar content scrolled. Am I missing something?

**Comment by tobias-r** [comment]
Maybe it's a problem with firefox on a Mac.

But I am positive that the background weirdly (not smoothly) scrolls with
it. For example if i flickscroll background stays for a bit, till the box
itself scrolls to the end, and then after a second it starts scrolling.
Weird enough! I tried to add stoppers in your code already, but nothing
worked. They seem to be in place.

The scroll is not at all smooth either, it kinda seems that everytime
between the scrolling hops the event is not prevented.

Same issue with this one - too bad:
http://manos.malihu.gr/tuts/custom-scrollbar-plugin/nested_scrollbars_demo.html

2013/9/19 Maciej Zubala notifications@github.com

**Comment by mzubala** [comment]
I checked your site on OSX FF (couple versions) and it works just fine. The second link is also fine. Looks like sth is wrong with your FF installation ;)
