### ISSUE TITLE
Resize Problem

### ISSUE THREAD

**Issue by nicholasleblanc** [mzubala/jquery-custom-scrollbar#14]
I have a dynamically sized container in which I'm using customScrollbar.  After dynamically resizing my container (and some other elements within), I call .customScrollbar('resize') (which is attached to an element within the container).  The problem that I'm having is that the actual scroll height of the customScrollbar element is almost 2x the size it should be, meaning that there is always tons of extra white space at the bottom.  This problem only seem's to occur when I'm hiding or showing a second customScrollbar element (not sure if it's related).

**Comment by mzubala** [comment]
I can't repeat it. Could you submit some js+html+css that causes this bug?
