### ISSUE TITLE
Fixed thumb size

### ISSUE THREAD

**Issue by alleknalle** [mzubala/jquery-custom-scrollbar#17]
I don't know if it's already possible, but I would like to give the vertical thumb a fixed height. When I do this, my thumb stops halfway the page and not at the end.

Could you make this possible to do?

**Comment by mzubala** [comment]
There is only an option to have min-height (or min-width) of the thumb just in case you have so big list that thumb is almost invisible. You define that in css. 

Why do you want to have fixed thumb size? Thumb size is auto-calculated to inform your users how long is the whole content and its visible part.

**Comment by alleknalle** [comment]
It's something my client requires. She wants the thumb to be an image. And now the image stops halfway.

**Comment by mzubala** [comment]
I added 2 extra options: fixedThumbHeight and fixedThumbWidth. They're described in the documentation.

**Comment by alleknalle** [comment]
Thanks!
