### ISSUE TITLE
Wordpress Version

### ISSUE THREAD

**Issue by kaynenh** [mzubala/jquery-custom-scrollbar#18]
Hey,

Great plugin! Based on a client's need for a transparent scrollbar across their site, I've created a wordpress version of the plugin located here: https://github.com/kaynenh/custom-scrollbar.

I just wanted to make sure you were aware of my plugin. Since I didn't see a specific license, I also wanted to make sure you were okay with it.

Thanks again!

**Comment by mzubala** [comment]
Hi

Sure, I don't mind. Good job with the wordpress plugin! I added license (MIT) info to the readme file.
