### ISSUE TITLE
Background scroll

### ISSUE THREAD

**Issue by tobias-r** [mzubala/jquery-custom-scrollbar#19]
Hi,

I was the one suggesting the scroll in the background whenever the container itself is scrolled to the end.

Now it is always like that. Would you think about making this configurable (an option)?

I think in some cases it's really useful, in some it isn't!

Thanks
Tobi

**Comment by mzubala** [comment]
Ok, I'll think about it. Do you think it should be on or off by default?

**Comment by tobias-r** [comment]
Puh, tough question. I think if you got a scrollbar in a submenu or anything, content in background shouldn't be scrolled. However if you got a box in a long list, for example comments with a scrollbar (see Google Plus, they do it, check https://plus.google.com/+Nexus/posts) then it is crucial.

Default, hmmm, maybe default on and call option preventBackgrounScroll or anything?

**Comment by mzubala** [comment]
I added preventDefaultScroll option. By default it's set to false (background scrolling is enabled). If you set it to true it will disable background scrolling.

**Comment by manchaary** [comment]
Hello,
Windows 8.1 " { preventDefaultScroll : true }" not working in chrome
