### ISSUE TITLE
MaxOverviewPosition

### ISSUE THREAD

**Issue by tobias-r** [mzubala/jquery-custom-scrollbar#20]
Could you put

calculateMaxOverviewPosition:function(){
return Math.max(0,this.sizing.size(this.scrollable.$overview)-this.sizing.size(this.scrollable.$viewPort))
}

Otherwise it's not working for me!!
Content moves to bottom, but i need it to stick to the top.

Think about it. I couldn't see any disadvantages, MaxOverviewPos should not be smaller than 0!

Thanks

**Comment by mzubala** [comment]
Max overview position is calculated like this:

<code>
calculateMaxOverviewPosition: function () {
   return this.sizing.size(this.scrollable.$overview) - this.sizing.size(this.scrollable.$viewPort);
}
</code>

If it is < 0, it means that <code>this.sizing.size(this.scrollable.$overview) < this.sizing.size(this.scrollable.$viewPort);</code>

In such case the scrollbar shouldn't appear. I'm guessing that you resized your scrollable component perhaps by dynamically adding some stuff and forgot to call:
<code>
$("your-element").customScrollbar("resize")
</code>

**Comment by tobias-r** [comment]
I am not quite sure, but I think the case is, that I need the content to be scrolled to bottom, unless, there is no scrollbar. Then it should stick to the top.
So a list, which builts up from top, but if it's getting longer than the container (scroll added), then it should always scroll to bottom. I think for that I simply call scrollToY(100000).

Without my changes, even one line sticks to bottom, plus everytime i add a line and call resize, content moves again from top to bottom - a weird behaviour.

The 10 Characters will do only good ;-)

**Comment by mzubala** [comment]
You can pass an extra boolean <code>keepPosition</code> param to resize. If you call:

<code>$("your-element").customScrollbar("resize", true)</code>

it will leave the scrolled content in the same position.

**Comment by tobias-r** [comment]
Yes, I know, but I only want to keep the position, if the container does not require a scrollbar. After the resize command is supposed to scroll to bottom. And I don't see any other way to do this.

**Comment by mzubala** [comment]
If the container does not require a scrollbar then it doesn't matter if you pass keepPosition equal to true or false cause it will always show the whole content. 

I think what we need to have is not a boolean param to resize but some enum <code>position</code> param that would say what to do after resize. You could pass: "top" and it would move the scrollbar top after resize, "bottom" would move the scrollbar to the bottom, "keep" would make it show the same content as before resize and "proportional" would keep the same scroll percent as before resize. Do you think that would help you?

**Comment by tobias-r** [comment]
Dunno, probably not.
You see you got a div with lets say 500px height and you add line by line followed by scrollToBottom (or, cos you dont have it scrollToY(1000000).

Before the content reaches 500px it should be aligned top, after always the newest entry (bottom entry) has to be shown, so the container need to scroll from its current position to bottom.

Works with Math.max, else not

**Comment by mzubala** [comment]
Oh, ok I now get what your problem is. You call scrollToY before the scrollbar appears and content moves down which is a bug. I don't know if Math.max is a good fix for that but I'll definitely fix it.
