### ISSUE TITLE
Is not working with .ScrollTo  function

### ISSUE THREAD

**Issue by sugappriya** [mzubala/jquery-custom-scrollbar#21]

**Comment by mzubala** [comment]
What do you mean by .ScrollTo function?

Refer to http://jquery-custom-scrollbar.rocketmind.pl/scrolling_programmatically.html demo to see how to scroll programmatically. 

If you found a bug, please provide some code sample that shows how to repeat it.

**Comment by sugappriya** [comment]
Hey Frd,

Got that..Thank you
