### ISSUE TITLE
Max-Height

### ISSUE THREAD

**Issue by tobias-r** [mzubala/jquery-custom-scrollbar#24]
If I put CSS 'max-height' attribute on a container (without height), scroller is not working.

Cheers

**Comment by tobias-r** [comment]
Hi, perfect it works so far.

However I realized on little problem I'd like to discuss:
- A layer has the css max-height 200px, the content is 100px high, so the effective displayed height is 100px.
- Then I call customScrollbar
- After the content of scrol layer changes to 150px height (e.g. click on "more", or a "plus" or whatever).
- Now calling the "resize" adjusts the scrollbars, but not the height of the layer. So the layer stays 100px with a content of 150px and a max-height of 200px.

Maybe with a resize-call the layer height should be readjusted as well, if smaller than max-height of course??

What do you think?

```
Tobias
```

**Comment by mzubala** [comment]
it should work as you expect now

**Comment by tobias-r** [comment]
I am experiencing problems now with containers without max-height.

The height in the Viewport-layer is not set in my case? Can you reproduce this?

**Comment by mzubala** [comment]
If you don't set max-height you have to set height. One of them needs to be set. I'm not seeing any problems. Would be great if you could submit some code that causes the error.

**Comment by tobias-r** [comment]
The error occured with the update - I didn't change anything and it worked before.
I cannot provide a test dummy right now, but I can give you more details:
- Height is set (absolute, I don't think relative heights are working, btw)
- Scrollable container is position absolute
- Viewport height is missing, by adding the viewport height manually, everything works fine.
- Chrome on Mac

**Comment by tobias-r** [comment]
I hate to say, but it was my bad. In the end a timing problem occured cos of different reasons.
Sorry for the shock ;-)
