### ISSUE TITLE
preventDefaultScroll and Firefox

### ISSUE THREAD

**Issue by influxweb** [mzubala/jquery-custom-scrollbar#26]
Great plugin. I am testing this out and have found that when setting "preventDefaultScroll" to true, the expected function works in all browsers except Firefox. Firefox will scroll the page as you scroll the scrollable element.

**Comment by mzubala** [comment]
Are you sure about this? I've checked it (http://jquery-custom-scrollbar.rocketmind.pl/prevent_default_scroll.html) on FF 25.0.1 and it works as expected. What version of FF and what OS are you using?

**Comment by influxweb** [comment]
Hi Maciej,

I'm using Firefox 25.0.1 on Windows Vista. It also seems like, with the default settings, the page will scroll when trying to scroll in a box as well.

**Comment by mzubala** [comment]
That's weird. It works for me on FF 25.0.1 on Win 7. With the default setting it should scroll the main page (or parent container) when you are in the box only after you reached the end of the box.

**Comment by titzu** [comment]
Hi Maciej, 
I can confirm that on FF 33.1 (windows 8) this is not working (the main page scrolls with the scrollable element event if you didnt reach the end of the box). IE and Chrome are ok.
