### ISSUE TITLE
Functions scrollByX(x) and scrollByY(y) not defined

### ISSUE THREAD

**Issue by dcusimano** [mzubala/jquery-custom-scrollbar#28]
Functions scrollByX(x) and scrollByY(y) mentioned in the documentation do not work. They are not defined in the .js file. The documentation appears to be wrong. What functions are to be called to programmatically scroll horizontally / vertically by N pixels?

**Comment by dcusimano** [comment]
The above comment refers to build 0.5.5. I just tried the master and it works with that version. Thanks.

**Comment by mzubala** [comment]
Yes, they've just been added lately.
