### ISSUE TITLE
All html elements selected when mouse outside

### ISSUE THREAD

**Issue by vijay-vanecha** [mzubala/jquery-custom-scrollbar#29]
'not-selectable' class and attribute 'unselectable' is added but still other html elements selected when mouse outside

**Comment by mzubala** [comment]
I'm not sure what you mean. Please describe it in more detail.

**Comment by vijay-vanecha** [comment]
I mean when i click on scroll thumb and move mouse outside of scroll bar area, all text and content on page get selected.

**Comment by mzubala** [comment]
1. When you click on the thumb and move the mouse nothing is selected. 
2. When you click inside scrollable area and move the mouse content inside and outside is selected.

1 is fine. That's who native scrollbar behaves.
2 is different from native scrollbars which only select content inside the scrolled container and scroll it if you move the mouse outside the viewport. I'll think how to implement that.

**Comment by vijay-vanecha** [comment]
Thanks for help,

I found that this bug is reproduced only on Firefox. I am attaching image for more clarification. When i debugging i found that 'not-selectable' class and 'unselectable' attribute is already added but still all elements of page is selectable.

**Comment by clphillips** [comment]
To fix the select issue change.

``` js
      startMouseMoveScrolling:function (event) {
        ...
      },
```

to:

``` js
      startMouseMoveScrolling:function (event) {
        ...
        event.preventDefault();
      },
```

Additionally, .not_selectable and the attribute unselectable="on" should really be set on **body** not **html**. You can fix this in the same function, as well as in **stopMouseMoveScrolling**.

**Comment by vijay-vanecha** [comment]
It's working now. Thanks a lot clphillips & Maciej Zubala for your support.
