### ISSUE TITLE
Increasing scroll speed

### ISSUE THREAD

**Issue by sachingupta006** [mzubala/jquery-custom-scrollbar#3]
Is there a way by which I can play around with the scroll speed, the default one is too slow.

**Comment by mzubala** [comment]
There are multiple ways of scrolling: mouse drag, mouse wheel, keyboard, touch. Which one is too slow? Do you mean any particular device?

**Comment by sachingupta006** [comment]
I am checking it on my laptop, there seems to be no handler where I can define the scroll speed.

**Comment by mzubala** [comment]
But are you using keyboard, touchpad or regular mouse drag or mouse wheel?

**Comment by RicardoStrobel** [comment]
mousewheel and trackpad are slow

**Comment by mzubala** [comment]
I added two new config params: swipeSpeed and wheelSpeed. You can use them to adjust touch and mouse wheel scrolling speed.
