### ISSUE TITLE
Is not working when we append the data on the fly

### ISSUE THREAD

**Issue by sugappriya** [mzubala/jquery-custom-scrollbar#30]
Hey Frd,

Custom scrollbar is not working when we append the data using javascript dynamically.

Please any help?

**Comment by mzubala** [comment]
After you append data you have to call resize function as described in the documentation to let the scrollbar know it needs to update.

**Comment by sugappriya** [comment]
Hey its not working for me.Can you guide me?

**Comment by mzubala** [comment]
Take a look at the demo: 
http://jquery-custom-scrollbar.rocketmind.pl/expandable_list.html
It shows how to call resize function.
