### ISSUE TITLE
updateOn parent resize feature

### ISSUE THREAD

**Issue by Pixelalb** [mzubala/jquery-custom-scrollbar#31]
Thank you for the plugin!

I'd like to update when the parent of scrollable div is resized.
Is it possible to achieve this? (similar to updateOnWindowResize)

Thank you!

**Comment by mzubala** [comment]
It's not possible to listen to dom changes, so whenever contents of your div change causing size change, you have to call the resize function yourself. 

$("....").customScrollbar("resize")

This will update the scrollbar to the new size. 
There's a demo that shows how to do it. You can check it out here:

http://jquery-custom-scrollbar.rocketmind.pl/expandable_list.html

The source code is in the repo inside demos folder.

**Comment by Pixelalb** [comment]
Thank you!
