### ISSUE TITLE
Div content gets selected upon scroll.

### ISSUE THREAD

**Issue by HarisBilal** [mzubala/jquery-custom-scrollbar#32]
If I clcik on scroller thumb and drag it down or top. the contnet in the div on which scroller is applied gets selected. 

If you can help me in this regard It will be highly appreciable.

![selection](https://f.cloud.github.com/assets/6557189/2054902/a12f9e1e-8abc-11e3-84d6-66d6e463c346.png)

**Comment by mzubala** [comment]
Someone already reported that before in #29. That was only firefox problem. Do you have it in other browsers? I made a fix that was suggested there. Please try the latest source to see if that helps.

**Comment by HarisBilal** [comment]
Thanks for the reply, I am having this problem in IE. Testing this on IE 8. I went through the replies you provided in the issue no 29. but I am not clear about how to implement it.

If you can help me in:
1. How to place 'not-selectable' class and attribute 'unselectable'.
2. You mentioned startMouseMoveScrolling function. but I am unable to find it in your js file. 

Can you illustrate how to fix it by providing some steps.

It would be really help-full.

I am using this control in SharePoint 2013 environment.

This is how I placed script block in my master page:

![image](https://f.cloud.github.com/assets/6557189/2204388/85814c84-993b-11e3-8519-fea1c2354b05.png)

**Comment by mzubala** [comment]
@HarisBilal it seems that you're using a different plugin that this one ;) This plugin (https://github.com/mzubala/jquery-custom-scrollbar) doesn't select content  when scrolling out of the box. You don't have to implement anything, just switch to my plugin and you'll be fine ;)
