### ISSUE TITLE
On iPad all hover events are mixed and broken after $el.customScroll()

### ISSUE THREAD

**Issue by neTpyceB** [mzubala/jquery-custom-scrollbar#33]
After a lot of time spent on this issue, mor than a motnh a was creating workarounds....
So basically, fixed
"document..."
to
"this.scrollable.$element[0]..."
on line 310, so it's like:
this.scrollable.$element[0].addEventListener("touchmove", this.documentTouchmove);

Problem is that adding event listener to all document can break all other scripts. And adding event to exact scrollable element (well, is'n it what required?) - works ok.

This issue broke my site on on iPhones (4\5) and iPads.
Nowhere else.

**Comment by mzubala** [comment]
you're right, I pulled this fix, thanks for noticing!
