### ISSUE TITLE
Scroll bar not appearing on the page!

### ISSUE THREAD

**Issue by itsfaddy** [mzubala/jquery-custom-scrollbar#37]
Hi,

I have added the lines of code to js & css and also called the custom scroll bar function over the selector, but it isn't working. On checking the chrome developers tool i was able to see that the scrollbar components/elements haven't even been added to the code. Could you help me out with this issue.

**Comment by itsfaddy** [comment]
I am loading the data on the fly using backbone and as one of suggestions given in an earlier issue reported was to use the resize function. I tried it but no luck..

**Comment by itsfaddy** [comment]
Got it resolved! The div was supposed to be scrollable and in my code the div's html were replaced with the data got from the backend! Thus the scroller components were getting replaced. Got it resolved by placing an inner div for the backend contents to be loaded with thus leaving the scroll bar components un-touched!

Great scrollbar i must say. simple n elegant.

Thanks,
Faddy!

**Comment by mzubala** [comment]
"Great scrollbar i must say. simple n elegant."

Thanks! The idea was to build it this way ;)
