### ISSUE TITLE
Touch scrolling is too fast (fix)

### ISSUE THREAD

**Issue by martinkorner** [mzubala/jquery-custom-scrollbar#4]
If it helps anyone else; I found that the touch/drag scrolling speed was much faster than it would normally be in the browser (Google Chrome on touch-screen PC).

This can be fixed by just changing line 406:

``` js
this.moveScroll(event.touches[0], -1);
```

to:

``` js
this.moveScroll(event.touches[0], -this.ratio);
```

I haven't tested this on mobile devices as this was not relevant in my current project.

**Comment by mzubala** [comment]
Thanks for this suggestion. I'll check that on mobile devices.

**Comment by mzubala** [comment]
Yes it works better on mobile devices. I'm pulling your code in.

**Comment by martinkorner** [comment]
Great, glad I could help :+1:
