### ISSUE TITLE
How to call multiple methods in scrollbar initializing?

### ISSUE THREAD

**Issue by justin-john** [mzubala/jquery-custom-scrollbar#40]
Can we call more than one method in scrollbar initializing?

_For example_
I have to call `scrollToY` and `ScrollToX` parallely. I know there is `scrollToXY` method present here, that is not in my scope. We can do it like below, but it can initialize one method at a time.

```
$(".container").customScrollbar("scrollToY", 200);
//OR
$(".container").customScrollbar("scrollToX", 200);
```

Can I call something like below?

```
$(".container").customScrollbar({ scrollToX:  200, scrollToY: 150});
```

**Comment by mzubala** [comment]
No, you have to call one after another like in your first example.

**Comment by justin-john** [comment]
@mzubala Thank you.
