### ISSUE TITLE
scrollToElement location (question)

### ISSUE THREAD

**Issue by ghost** [mzubala/jquery-custom-scrollbar#5]
Polish (author of this project are Pole):

Witaj,
wiem, iż nie jest to błąd, ale nie bardzo wiem jak inaczej się z Tobą skontaktować.
Zainstalowałem na stronie Twój pasek przewijania i praktycznie wszystko jest dobrze, ale chciałbym, aby funkcja "scrollToElement" przenosiła do tego elementu tak, aby był on na górze, a nie na dole. Patrzyłem trochę w kod JS, ale to nie moja działka i jak nie ma konkretnych wartości to nie ogarniam :)

Załączę Ci obrazki:
- jak to wygląda po przeniesieniu:

![1](https://f.cloud.github.com/assets/5213746/947385/adf54916-0351-11e3-8726-acbe7ff51a4f.jpg)
- jak chciałbym, aby to wyglądało:

![2](https://f.cloud.github.com/assets/5213746/947380/9877409e-0351-11e3-809c-23e353f48182.jpg)

Oraz fragment kodu: http://www.curseforge.com/paste/8339/

Z góry dzięki za pomoc,
Pozdrawiam

**Comment by mzubala** [comment]
Masz rację - lepiej żeby element do którego scrollujemy zawsze pokazywał sie na górze. Nowa wersja 0.5.2 zawiera poprawkę.

**Comment by ghost** [comment]
Dzięki :)
