### ISSUE TITLE
Wrong working on Google Chrome and Safari

### ISSUE THREAD

**Issue by ghost** [mzubala/jquery-custom-scrollbar#6]
Polish (author of this project are Pole):

Witaj,
pomyślałem sobie, iż posprawdzam sobie dzisiaj jak wygląda stronka, którą robię na innych przeglądarkach (oprócz IE - nie działa mi :/) i znalazłem pewien problem, a mianowicie na Google Chrome i Safari nie działa przypisywanie lokalnych stylów do pasków (np. wysokość, brak widoczności), co skutkuje również znacznym wolnym miejscem do przewijania pod faktyczną stroną.
W arkuszu stylów od Twojego paska zmieniałem tylko kolorystykę i ustawiałem brak animacji (transition normalnie używam do niektórych elementów na stronie) w stylu nowoczesnym i po zmianach na Operze (normalnie z niej korzystam) oraz na Firefoxie wszystko jest tak jak powinno.

Możliwe, iż ten błąd występuje tylko u mnie - może coś źle zrobiłem.
Zamieszczam zrzut ekranu z Google Chrome:
![1](https://f.cloud.github.com/assets/5213746/951761/db858690-03ae-11e3-8bb0-1be15fefc278.jpg)

Liczę na odpowiedź w jaki sposób zaradzić tej niedogodności lub proszę o łatkę.
Pozdrawiam

**Comment by mzubala** [comment]
Z tego co widzę to jakoś dynamicznie (z animacją) ładujesz kontent zakładki. Musisz zainicjować scrollbara po tym jak kontent w całości zostanie pokazany. W kosoli chroma wywyołałem:

jQuery("#tekst3").customScrollbar("resize")

i wtedy scrollbar wygląda dobrze.

Czyli jak gdzieś w kodzie masz

jQuery("#tekst3").customScrollbar()

to upewnij się, że to zostanie wywołane dopiero po tym jak skończy się animacja.

**Comment by ghost** [comment]
Używam po prostu takiego czegoś:

dd, a, img, div, dt { 
  transition: all 0.5s cubic-bezier(0.42, 0, 0.58, 1) 0;
}

dziwne, że takie coś miało na to wpływ ;]
Dodam sobie po prostu do id "tekst3" brak animacji w css.

Dzięki, powinieneś napisać coś o tym w instrukcji lub zrobić FAQ ;)

@Edycja: a raczej musiałem dodać brak animacji do klasy "viewport"
