### ISSUE TITLE
Take the porn out of the demos

### ISSUE THREAD

**Issue by developering** [mzubala/jquery-custom-scrollbar#60]
It's irritating to be browsing a jquery plugin at work and have inappropriate pictures show up in the demo. Class it up a bit by using something benign.

**Comment by scottmanningstorm** [comment]
Yes, I to was a little taken back by this when viewing them at work.

**Comment by damiencorpataux** [comment]
Note that this is nudity, not porn.

**Comment by Daerigorn** [comment]
[Lenna On Wikipedia](https://en.wikipedia.org/wiki/Lenna)
"Lenna or Lena is the name given to a standard test image widely used in the field of image processing since 1973"
So its tradition, or convention or something ... so its a legitimate photo to be using.
But I do see what you're saying
