### ISSUE TITLE
scoll-bar margin

### ISSUE THREAD

**Issue by haydnhkim** [mzubala/jquery-custom-scrollbar#7]
hello,

I love this project!
I want to give margin to `.scroll-bar`. so, I gave margin like this.

```
.scrollable.topfost-skin .scroll-bar.horizontal {
    margin: 0 10px;
}
```

then, `.thumb` move element out of parent..
how can I give margin?

thanks!

\+ add

```
.scrollable.topfost-skin .scroll-bar.horizontal {
    border:1px solid #000;
}
```

when `.scroll-bar` has border, `.scroll-bar`'s width included border width.
I think `.scroll-bar` width calculate code need to be change outerWidth().
if that the case, maybe outerWidth(true) do fix `.scroll-bar`'s margin too.

**Comment by mzubala** [comment]
Right now the scrollbar is supposed to have the same width/height (depending on orientation) as the view port, so you can't really add margin. However I see your point and I think that you should be able to set smaller width/height (and therefore margin) of the scrollbar and I'll change the code to allow it.

**Comment by haydnhkim** [comment]
ok! thanks.
