### ISSUE TITLE
Option to control scroll speed

### ISSUE THREAD

**Issue by sourcebits-chethankswamy** [mzubala/jquery-custom-scrollbar#8]
Hi,
First of all thanks for the great plugin. It will be really very helpful if you can let me know on how to add the animation speed when scrollTo or any other methods are used, for example,
$(".container").customScrollbar("scrollTo","200", "#some-element-inside-container");
where "200" is the animation speed of the scroll.

Thanks
Chethan K

**Comment by mzubala** [comment]
Hey Chethan,

You need to modify 

Scrollable.scrollTo
and 
Scrollbar.scrollToElement 

methods to take an extra param and pass it through to 

Scrollbar.scrollTo

method. And then in Scrollbar.scrollTo you'd need to use jquery animate function to create animation effect.

That's an interesting feature - thanks for suggestion!. I'll add it to my todo list but if you do it earlier, pls submit pull request.

**Comment by mzubala** [comment]
I added this feature. Now you can pass animationSpeed when initializing the plugin. By default it's set to 300 ms.

**Comment by sourcebits-chethankswamy** [comment]
Thanks a lot for the feature and very quick reply Mzubala :) its working like a charm.
